// Frontend_avec_post/Frontend/src/pages/auth/VerifyCode.tsx
import { Button } from "@/components/ui/button"
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { useState, useEffect, useRef } from 'react'
import { Mail, Lock } from 'lucide-react'
import {authService} from '@/services/authService'
import { useToast } from "@/hooks/use-toast"

const VerifyCode = () => {
  const { toast } = useToast()
  const navigate = useNavigate()
  const location = useLocation()
  const email = location.state?.email || ''
  const [code, setCode] = useState(['', '', '', '', '', ''])
  const [error, setError] = useState('')
  const [countdown, setCountdown] = useState(60)
  const [resending, setResending] = useState(false)
  const [verifying, setVerifying] = useState(false)
  const [activeInput, setActiveInput] = useState(null)
  const inputRefs = useRef([])

  const codeComplete = code.every(digit => digit !== '')

  // Initialize countdown
  useEffect(() => {
    if (!email) {
      navigate('/auth/signup')
      toast({
        title: "Erreur",
        description: "Veuillez d'abord remplir le formulaire d'inscription.",
        variant: "destructive"
      })
    }

    let interval = null
    if (countdown > 0) {
      interval = setInterval(() => {
        setCountdown(prev => prev - 1)
      }, 1000)
    }
    
    return () => clearInterval(interval)
  }, [email, navigate, toast, countdown])

  // Focus first input on mount
  useEffect(() => {
    if (inputRefs.current[0]) {
      inputRefs.current[0].focus()
    }
  }, [])

  // Handle input change
  const handleInputChange = (index, e) => {
    const value = e.target.value.replace(/\D/g, '')
    const newCode = [...code]
    newCode[index] = value
    setCode(newCode)
    setError('')

    // Move to next input
    if (value && index < 5) {
      inputRefs.current[index + 1]?.focus()
    }
  }

  // Handle backspace
  const handleBackspace = (index, e) => {
    if (e.key === 'Backspace' && !code[index] && index > 0) {
      inputRefs.current[index - 1]?.focus()
    }
  }

  // Handle arrow keys
  const handleKeyDown = (index, e) => {
    if (e.key === 'ArrowRight' && index < 5) {
      inputRefs.current[index + 1]?.focus()
    }
    if (e.key === 'ArrowLeft' && index > 0) {
      inputRefs.current[index - 1]?.focus()
    }
  }

  // Handle paste event
  const handlePaste = (e) => {
    e.preventDefault()
    const paste = e.clipboardData.getData('text').replace(/\D/g, '')
    
    if (paste.length === 6) {
      const newCode = paste.split('').slice(0, 6)
      setCode(newCode)
      inputRefs.current[5]?.focus()
    }
  }

  // Resend code
  const resendCode = async () => {
    setResending(true)
    setError('')
    
    try {
      const response = await authService.resendOtp(email)
      
      if (response.data?.error) {
        setError(response.data.error)
      } else {
        setCountdown(60)
        setCode(['', '', '', '', '', ''])
        inputRefs.current[0]?.focus()
        toast({
          title: "Code renvoyé!",
          description: "Un nouveau code de vérification a été envoyé."
        })
      }
    } catch (err) {
      setError(err.response?.data?.error || 'Erreur lors de l’envoi du code.')
      toast({
        title: "Erreur",
        description: "Impossible de renvoyer le code de vérification.",
        variant: "destructive"
      })
    } finally {
      setResending(false)
    }
  }

  // Verify code
  const verifyCode = async () => {
    if (!codeComplete) return
    
    setVerifying(true)
    setError('')
    
    try {
      await authService.verifyUser({
        email,
        verificationCode: code.join('')
      })
      
      toast({
        title: "Vérification réussie!",
        description: "Votre compte a été vérifié avec succès."
      })
      
      setTimeout(() => {
        navigate('/auth')
      }, 1500)
    } catch (err) {
      setError(err.response?.data?.error || 'Code incorrect. Veuillez réessayer.')
      setCode(['', '', '', '', '', ''])
      inputRefs.current[0]?.focus()
      
      toast({
        title: "Erreur",
        description: "Code de vérification invalide.",
        variant: "destructive"
      })
    } finally {
      setVerifying(false)
    }
  }

  // Go back
  const goBack = () => {
    navigate(-1)
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-purple-50 via-white to-blue-50">
      <div className="w-full max-w-md p-8 space-y-6 bg-white/80 backdrop-blur-lg rounded-2xl shadow-lg border border-gray-100">
        <div className="text-center">
          <h1 className="text-3xl font-bold bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
            Vérification requise
          </h1>
          <p className="text-gray-500 mt-2">
            Nous avons envoyé un code à 6 chiffres à<br />
            <strong className="text-blue-600">{email}</strong>
          </p>
        </div>

        {error && (
          <div className="p-3 text-sm text-red-700 bg-red-50 rounded-lg">
            {error}
          </div>
        )}

        <div className="flex flex-col items-center justify-center space-y-6">
          <div 
            className="code-inputs flex justify-center gap-3"
            onPaste={handlePaste}
          >
            {code.map((digit, index) => (
              <input
                key={index}
                ref={el => inputRefs.current[index] = el}
                type="text"
                inputMode="numeric"
                maxLength={1}
                value={digit}
                onChange={(e) => handleInputChange(index, e)}
                onKeyDown={(e) => handleBackspace(index, e)}
                onKeyUp={(e) => handleKeyDown(index, e)}
                onFocus={() => setActiveInput(index)}
                onBlur={() => setActiveInput(null)}
                className={`w-14 h-16 text-center text-2xl font-semibold border-2 rounded-lg transition-all
                  ${error ? 'border-red-500' : activeInput === index ? 'border-purple-500 ring-2 ring-purple-200' : 'border-gray-300'}
                `}
              />
            ))}
          </div>

          <div className="w-full text-center">
            {countdown > 0 ? (
              <p className="text-gray-500 text-sm">
                Nouveau code disponible dans {countdown}s
              </p>
            ) : (
              <button
                type="button"
                onClick={resendCode}
                disabled={resending}
                className="text-purple-600 hover:text-purple-700 text-sm font-medium flex items-center justify-center gap-1 disabled:opacity-50"
              >
                {resending && (
                  <div className="w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin"></div>
                )}
                Renvoyer le code
              </button>
            )}
          </div>

          <div className="flex justify-between w-full mt-6">
            <Button
              variant="outline"
              onClick={goBack}
              className="flex items-center gap-2 text-purple-600 border-purple-200 hover:bg-purple-50"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="m12 19-7-7 7-7"></path>
                <path d="M19 12H5"></path>
              </svg>
              Retour
            </Button>
            
            <Button
              onClick={verifyCode}
              disabled={!codeComplete || verifying}
              className="bg-purple-600 hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {verifying && (
                <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin mr-2"></div>
              )}
              Vérifier
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}

export default VerifyCode

// We_Connect-main/src/pages/auth/VerifyCode.vue
<template>
    <div class="auth-container">
      <div class="auth-card">
        <div class="auth-header">
          <h1>Vérification requise</h1>
          <p>
            Nous avons envoyé un code à 6 chiffres à<br>
            <strong>{{ email }}</strong>
          </p>
        </div>
  
        <div class="verify-form">
          <div class="code-inputs" @paste.prevent="handlePaste">
            <input
              v-for="i in 6"
              :key="i"
              v-model="code[i-1]"
              @input="handleInput(i, $event)"
              @keydown.delete="handleBackspace(i, $event)"
              @keydown="handleKeyDown(i, $event)"
              @focus="activeInput = i-1"
              @blur="activeInput = null"
              type="text"
              maxlength="1"
              inputmode="numeric"
              pattern="[0-9]*"
              :class="{ 'input-error': error && !code[i-1] }"
              ref="codeInputs"
            />
          </div>
  
          <div class="code-actions">
            <p v-if="countdown > 0" class="countdown">
              Nouveau code disponible dans {{ countdown }}s
            </p>
            <button
              v-else
              @click="resendCode"
              class="resend-btn"
              :disabled="resending"
            >
              <span v-if="!resending">Renvoyer le code</span>
              <span v-else class="loading-spinner">
                <svg class="spinner small" viewBox="0 0 50 50">
                  <circle class="path" cx="25" cy="25" r="20" fill="none" stroke-width="5"></circle>
                </svg>
              </span>
            </button>
  
            <p v-if="error" class="error-msg">{{ error }}</p>
          </div>
  
          <div class="action-buttons">
            <button @click="goBack" class="back-btn">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="m12 19-7-7 7-7"></path>
                <path d="M19 12H5"></path>
              </svg>
              Retour
            </button>
  
            <button
              @click="verifyCode"
              class="verify-btn"
              :disabled="!isCodeComplete || verifying"
            >
              <span v-if="!verifying">Vérifier</span>
              <span v-else class="loading-spinner">
                <svg class="spinner" viewBox="0 0 50 50">
                  <circle class="path" cx="25" cy="25" r="20" fill="none" stroke-width="5"></circle>
                </svg>
              </span>
            </button>
          </div>
        </div>
      </div>
    </div>
  </template>
  
  <script setup>
  import { ref, computed, onMounted, onUnmounted } from 'vue'
  import { useRouter, useRoute } from 'vue-router'
  import authService from '@/Services/authService'
  
  const router = useRouter()
  const route = useRoute()
  
  const email = route.query.email || ''
  const code = ref(Array(6).fill(''))
  const codeInputs = ref([])
  const activeInput = ref(null)
  const countdown = ref(60)
  const resending = ref(false)
  const verifying = ref(false)
  const error = ref('')
  let countdownInterval = null
  
  const isCodeComplete = computed(() => {
    return code.value.every(c => c !== '')
  })
  
  const startCountdown = () => {
    countdown.value = 10
    countdownInterval = setInterval(() => {
      if (countdown.value > 0) {
        countdown.value--
      } else {
        clearInterval(countdownInterval)
      }
    }, 1000)
  }
  
  const handleInput = (index, event) => {
    const value = event.target.value.replace(/\D/g, '')
    code.value[index - 1] = value
  
    if (value && index < 6) {
      codeInputs.value[index]?.focus()
    }
  }
  
  const handleBackspace = (index, event) => {
    if (event.key === 'Backspace' && !code.value[index - 1] && index > 1) {
      codeInputs.value[index - 2]?.focus()
    }
  }
  
  const handleKeyDown = (index, event) => {
    if (event.key === 'ArrowRight' && index < 6) {
      codeInputs.value[index]?.focus()
    }
    if (event.key === 'ArrowLeft' && index > 1) {
      codeInputs.value[index - 2]?.focus()
    }
  }
  
  const handlePaste = (event) => {
    const paste = event.clipboardData.getData('text').replace(/\D/g, '')
    if (paste.length === 6) {
      code.value = paste.split('').slice(0, 6)
      codeInputs.value[5]?.focus()
    }
  }
  
  const resendCode = async () => {
    resending.value = true
    error.value = ''
    try {
      const response = await authService.resendOtp(email)
      if (response.data?.error) {
        error.value = response.data.error
      } else {
        startCountdown()
        code.value = Array(6).fill('')
        codeInputs.value[0]?.focus()
      }
    } catch (err) {
      error.value = err.response?.data?.error || 'Erreur lors de l’envoi du code.'
    } finally {
      resending.value = false
    }
  }
  const verifyCode = async () => {
  if (!isCodeComplete.value) return

  verifying.value = true
  error.value = ''
  code.value = code.value.map(c => c.trim())

  try {
    // Use verifyOtp and send { email, verificationCode }
    await authService.verifyOtp({
      email,
      verificationCode: code.value.join('')
    })
    router.push({ path: '/auth/signin', query: { verified: 'true' } })
  } catch (err) {
    error.value = err.response?.data?.error || 'Code incorrect. Veuillez réessayer.'
    code.value = Array(6).fill('')
    codeInputs.value[0]?.focus()
  } finally {
    verifying.value = false
  }
}
  
  const goBack = () => {
    router.go(-1)
  }
  
  onMounted(() => {
    startCountdown()
    codeInputs.value[0]?.focus()
  })
  
  onUnmounted(() => {
    if (countdownInterval) {
      clearInterval(countdownInterval)
    }
  })
  </script>
  <style scoped>
  .auth-container {
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: #f8fafc;
    padding: 1rem;
  }
  
  .auth-card {
    width: 100%;
    max-width: 28rem;
    background: white;
    border-radius: 1rem;
    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    padding: 2rem;
  }
  
  .auth-header {
    text-align: center;
    margin-bottom: 2rem;
  }
  
  .auth-header h1 {
    font-size: 1.5rem;
    font-weight: 600;
    color: #1e293b;
    margin-bottom: 0.5rem;
  }
  
  .auth-header p {
    color: #64748b;
    font-size: 0.875rem;
    line-height: 1.5;
  }
  
  .auth-header strong {
    color: #3b82f6;
    font-weight: 500;
  }
  
  .verify-form {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }
  
  .code-inputs {
    display: flex;
    justify-content: center;
    gap: 0.75rem;
  }
  
  .code-inputs input {
    width: 3rem;
    height: 3.5rem;
    text-align: center;
    font-size: 1.25rem;
    font-weight: 600;
    border: 1px solid #e2e8f0;
    border-radius: 0.5rem;
    background-color: #f9fafb;
    transition: all 0.2s;
  }
  
  .code-inputs input:focus {
    outline: none;
    border-color: #3b82f6;
    box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
    animation: pulse 1.5s infinite;
  }
  
  .input-error {
    border-color: #ef4444 !important;
    background-color: #fef2f2;
  }
  
  .code-actions {
    text-align: center;
  }
  
  .countdown {
    color: #64748b;
    font-size: 0.875rem;
  }
  
  .resend-btn {
    color: #3b82f6;
    font-weight: 500;
    background: none;
    border: none;
    cursor: pointer;
    font-size: 0.875rem;
    transition: color 0.2s;
  }
  
  .resend-btn:hover:not(:disabled) {
    color: #2563eb;
    text-decoration: underline;
  }
  
  .resend-btn:disabled {
    opacity: 0.7;
    cursor: not-allowed;
  }
  
  .error-msg {
    color: #ef4444;
    font-size: 0.875rem;
    margin-top: 0.5rem;
  }
  
  .action-buttons {
    display: flex;
    justify-content: space-between;
    margin-top: 1rem;
  }
  
  .back-btn {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    color: #3b82f6;
    background: none;
    border: none;
    font-weight: 500;
    cursor: pointer;
    padding: 0.5rem 1rem;
    border-radius: 0.5rem;
    transition: background-color 0.2s;
  }
  
  .back-btn:hover {
    background-color: #f8fafc;
  }
  
  .verify-btn {
    background-color: #3b82f6;
    color: white;
    border: none;
    padding: 0.75rem 1.5rem;
    border-radius: 0.5rem;
    font-weight: 500;
    cursor: pointer;
    transition: background-color 0.2s;
    min-width: 8rem;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  
  .verify-btn:hover:not(:disabled) {
    background-color: #2563eb;
  }
  
  .verify-btn:disabled {
    opacity: 0.7;
    cursor: not-allowed;
  }
  
  .loading-spinner {
    display: flex;
    align-items: center;
    justify-content: center;
  }
  
  .spinner {
    animation: rotate 1.5s linear infinite;
  }
  
  .spinner.small {
    width: 1rem;
    height: 1rem;
  }
  
  .spinner .path {
    stroke: currentColor;
    stroke-linecap: round;
    animation: dash 1.5s ease-in-out infinite;
  }
  
  @keyframes rotate {
    100% {
      transform: rotate(360deg);
    }
  }
  
  @keyframes dash {
    0% {
      stroke-dasharray: 1, 150;
      stroke-dashoffset: 0;
    }
    50% {
      stroke-dasharray: 90, 150;
      stroke-dashoffset: -35;
    }
    100% {
      stroke-dasharray: 90, 150;
      stroke-dashoffset: -124;
    }
  }
  
  @keyframes pulse {
    0%, 100% {
      box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.3);
    }
    50% {
      box-shadow: 0 0 0 4px rgba(59, 130, 246, 0.1);
    }
  }
  </style>
