// We_Connect-main -/src/pages/ResetPassword.vue
<template>
    <div class="auth-page">
      <div class="auth-card">
        <div class="auth-header">
          <h1 class="auth-title">Nouveau mot de passe</h1>
          <p class="auth-subtitle">Pour <span class="user-email">{{ email }}</span></p>
        </div>
  
        <form @submit.prevent="submitNewPassword" class="auth-form">
          <div class="form-group">
            <label for="newPassword" class="label">Nouveau mot de passe</label>
            <div class="input-wrapper">
              <LockIcon class="input-icon" />
              <input
                id="newPassword"
                :type="showPassword ? 'text' : 'password'"
                placeholder="••••••••"
                class="input-field"
                v-model="newPassword"
                required
                minlength="8"
                autocomplete="new-password"
              />
              <button
                type="button"
                @click="showPassword = !showPassword"
                class="password-toggle"
                :aria-label="showPassword ? 'Cacher le mot de passe' : 'Afficher le mot de passe'"
              >
                <EyeIcon v-if="showPassword" class="icon" />
                <EyeOffIcon v-else class="icon" />
              </button>
            </div>
            <div v-if="newPassword" class="password-feedback">
              <div class="strength-meter">
                <div class="strength-segment" :class="{'active': passwordStrength >= 1}"></div>
                <div class="strength-segment" :class="{'active': passwordStrength >= 2}"></div>
                <div class="strength-segment" :class="{'active': passwordStrength >= 3}"></div>
              </div>
              <p class="strength-text" :class="strengthTextClass">
                {{ passwordStrengthText }}
                <span v-if="passwordStrength < 3" class="hint-text">(minimum 8 caractères avec majuscule et chiffre)</span>
              </p>
            </div>
          </div>
  
          <div class="form-group">
            <label for="confirmPassword" class="label">Confirmer le mot de passe</label>
            <div class="input-wrapper">
              <LockIcon class="input-icon" />
              <input
                id="confirmPassword"
                :type="showConfirmPassword ? 'text' : 'password'"
                placeholder="••••••••"
                class="input-field"
                v-model="confirmPassword"
                required
                autocomplete="new-password"
              />
              <button
                type="button"
                @click="showConfirmPassword = !showConfirmPassword"
                class="password-toggle"
                :aria-label="showConfirmPassword ? 'Cacher le mot de passe' : 'Afficher le mot de passe'"
              >
                <EyeIcon v-if="showConfirmPassword" class="icon" />
                <EyeOffIcon v-else class="icon" />
              </button>
            </div>
            <p v-if="passwordMismatch" class="error-message">
              Les mots de passe ne correspondent pas
            </p>
          </div>
  
          <button
            type="submit"
            class="submit-btn"
            :disabled="isSubmitting || passwordMismatch || !isPasswordStrong"
            :class="{ 'disabled': isSubmitting || passwordMismatch || !isPasswordStrong }"
          >
            <span v-if="!isSubmitting">Réinitialiser le mot de passe</span>
            <span v-else class="loading-spinner">
              <svg class="spinner" viewBox="0 0 50 50">
                <circle class="path" cx="25" cy="25" r="20" fill="none" stroke-width="5"></circle>
              </svg>
              Enregistrement...
            </span>
          </button>
        </form>
        <div v-if="errorMessage" class="error-message">
  {{ errorMessage }}
</div>
  
        <div class="auth-footer">
          <RouterLink to="/auth/signin" class="footer-link">
            <ArrowLeftIcon class="icon-sm" />
            Retour à la connexion
          </RouterLink>
        </div>
      </div>
    </div>
  </template>
  
  <script setup>
  import { ref, computed, onMounted } from 'vue'
  import { useRouter, useRoute } from 'vue-router'
  import { LockIcon, EyeIcon, EyeOffIcon, ArrowLeftIcon } from 'lucide-vue-next'
  import authService from '@/Services/authService' // <-- import your service
  
  const router = useRouter()
  const route = useRoute()
  const newPassword = ref('')
  const confirmPassword = ref('')
  const showPassword = ref(false)
  const showConfirmPassword = ref(false)
  const isSubmitting = ref(false)
  const errorMessage = ref('')
  const email = route.query.email || ''
  const token = route.query.token || ''
  
  const passwordMismatch = computed(() => {
    return !(newPassword.value && confirmPassword.value && newPassword.value == confirmPassword.value);
  })
  
  const passwordStrength = computed(() => {
    if (!newPassword.value) return 0
    if (newPassword.value.length < 6) return 1
    if (!/[A-Z]/.test(newPassword.value) || !/[0-9]/.test(newPassword.value) || !/[^A-Za-z0-9]/.test(newPassword.value)) return 2
    return 3
  })
  
  const passwordStrengthText = computed(() => {
    return ['Très faible', 'Moyen', 'Fort', 'Très fort'][passwordStrength.value] || ''
  })
  
  const strengthTextClass = computed(() => {
    return {
      'weak-text': passwordStrength.value === 1,
      'medium-text': passwordStrength.value === 2,
      'strong-text': passwordStrength.value === 3
    }
  })
  
  const isPasswordStrong = computed(() => passwordStrength.value >= 2)
  
  const submitNewPassword = async () => {
    errorMessage.value = ''
    isSubmitting.value = true
    try {
      await authService.resetPassword({
        email,
        newPassword: newPassword.value,
        confirmationPassword: confirmPassword.value
      })
      router.push('/auth/signin?reset=success')
    } catch (error) {
      errorMessage.value = error.response?.data?.error || error.message || 'Erreur lors de la réinitialisation'
    } finally {
      isSubmitting.value = false
    }
  }
  
  onMounted(() => {
    if (!email || !token) {
      router.push('/auth/forgot-password')
    }
  })
  </script>
  
  <style scoped>
  /* Base styles */
  .auth-page {
    display: flex;
    min-height: 100vh;
    align-items: center;
    justify-content: center;
    background-color: #f8fafc;
    padding: 1rem;
  }
  
  .auth-card {
    width: 100%;
    max-width: 28rem;
    background-color: white;
    border-radius: 0.75rem;
    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
    padding: 2.5rem;
  }
  
  .auth-header {
    text-align: center;
    margin-bottom: 2rem;
  }
  
  .auth-title {
    font-size: 1.5rem;
    font-weight: 600;
    color: #1e293b;
    margin-bottom: 0.5rem;
  }
  
  .auth-subtitle {
    color: #64748b;
    font-size: 0.875rem;
  }
  
  .user-email {
    font-weight: 500;
    color: #3b82f6;
  }
  
  .auth-form {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }
  
  .form-group {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }
  
  .label {
    font-size: 0.875rem;
    font-weight: 500;
    color: #334155;
  }
  
  .input-wrapper {
    position: relative;
  }
  
  .input-field {
    width: 100%;
    padding: 0.75rem 2.5rem 0.75rem 2.5rem;
    border: 1px solid #e2e8f0;
    border-radius: 0.5rem;
    font-size: 0.875rem;
    transition: all 0.2s;
  }
  
  .input-field:focus {
    outline: none;
    border-color: #3b82f6;
    box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
  }
  
  .input-icon {
    position: absolute;
    left: 0.75rem;
    top: 50%;
    transform: translateY(-50%);
    color: #94a3b8;
    width: 1.25rem;
    height: 1.25rem;
  }
  
  .password-toggle {
    position: absolute;
    right: 0.75rem;
    top: 50%;
    transform: translateY(-50%);
    background: none;
    border: none;
    color: #94a3b8;
    cursor: pointer;
    transition: color 0.2s;
  }
  
  .password-toggle:hover {
    color: #64748b;
  }
  
  .icon {
    width: 1.25rem;
    height: 1.25rem;
  }
  
  .icon-sm {
    width: 1rem;
    height: 1rem;
    margin-right: 0.25rem;
  }
  
  /* Password strength indicator */
  .password-feedback {
    margin-top: 0.5rem;
  }
  
  .strength-meter {
    display: flex;
    gap: 0.25rem;
    height: 0.25rem;
    margin-bottom: 0.25rem;
  }
  
  .strength-segment {
    flex: 1;
    border-radius: 0.125rem;
    background-color: #e2e8f0;
    transition: all 0.3s ease;
  }
  
  .strength-segment.active {
    background-color: currentColor;
  }
  
  .strength-segment:nth-child(1).active {
    color: #ef4444;
  }
  
  .strength-segment:nth-child(2).active {
    color: #f59e0b;
  }
  
  .strength-segment:nth-child(3).active {
    color: #10b981;
  }
  
  .strength-text {
    font-size: 0.75rem;
    font-weight: 500;
  }
  
  .weak-text {
    color: #ef4444;
  }
  
  .medium-text {
    color: #f59e0b;
  }
  
  .strong-text {
    color: #10b981;
  }
  
  .hint-text {
    color: #94a3b8;
    font-size: 0.6875rem;
  }
  
  /* Error message */
  .error-message {
    color: #ef4444;
    font-size: 0.75rem;
    margin-top: 0.25rem;
  }
  
  /* Submit button */
  .submit-btn {
    width: 100%;
    padding: 0.75rem;
    background-color: #3b82f6;
    color: white;
    border: none;
    border-radius: 0.5rem;
    font-weight: 500;
    font-size: 0.875rem;
    cursor: pointer;
    transition: background-color 0.2s;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  
  .submit-btn:hover:not(:disabled) {
    background-color: #2563eb;
  }
  
  .submit-btn.disabled {
    opacity: 0.7;
    cursor: not-allowed;
  }
  
  .loading-spinner {
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }
  
  .spinner {
    animation: rotate 1.5s linear infinite;
    width: 1.25rem;
    height: 1.25rem;
  }
  
  .spinner .path {
    stroke: white;
    stroke-linecap: round;
    animation: dash 1.5s ease-in-out infinite;
  }
  
  @keyframes rotate {
    100% {
      transform: rotate(360deg);
    }
  }
  
  @keyframes dash {
    0% {
      stroke-dasharray: 1, 150;
      stroke-dashoffset: 0;
    }
    50% {
      stroke-dasharray: 90, 150;
      stroke-dashoffset: -35;
    }
    100% {
      stroke-dasharray: 90, 150;
      stroke-dashoffset: -124;
    }
  }
  
  /* Footer link */
  .auth-footer {
    margin-top: 1.5rem;
    text-align: center;
  }
  
  .footer-link {
    display: inline-flex;
    align-items: center;
    color: #64748b;
    font-size: 0.875rem;
    text-decoration: none;
    transition: color 0.2s;
  }
  
  .footer-link:hover {
    color: #3b82f6;
  }
  </style>

// Nouveau dossier/ForumFinale - Copie - Copie (2)/Frontend/src/pages/auth/ResetPassword.tsx
import React, { useState, useEffect } from 'react';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Link, useNavigate, useLocation } from 'react-router-dom';
import { Lock, Eye, EyeOff, ArrowLeft } from 'lucide-react';
import {authService} from '@/services/authService';
import { useToast } from "@/hooks/use-toast";

const ResetPassword = () => {
  const { toast } = useToast();
  const navigate = useNavigate();
  const location = useLocation();

  const [newPassword, setNewPassword] = useState('');
  const [confirmationPassword, setconfirmationPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [showconfirmationPassword, setShowconfirmationPassword] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');

  // Extract email and token from URL query params
  const { email } = location.state || {};

  // Validate presence of required route state
  useEffect(() => {
    if (!email) {
      navigate('/auth/forgot-password');
    }
  }, [email, navigate]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setErrorMessage('');

    if (newPassword !== confirmationPassword) return;

    setIsSubmitting(true);

    try {
      await authService.resetPassword({
        email,
        newPassword,
        confirmationPassword,
      });

      toast({ title: "Mot de passe mis à jour" });
      setTimeout(() => {
        navigate('/auth');
      }, 1500);
    } catch (error) {
      const errorMsg = error.response?.data?.error || error.message;
      setErrorMessage(errorMsg);
      toast({ title: "Erreur", description: errorMsg, variant: "destructive" });
    } finally {
      setIsSubmitting(false);
    }
  };
  // Password strength logic
  const passwordStrength = () => {
    if (!newPassword) return 0;
    if (newPassword.length < 6) return 1;
    if (!/[A-Z]/.test(newPassword) || !/[0-9]/.test(newPassword) || !/[^A-Za-z0-9]/.test(newPassword)) return 2;
    return 3;
  };

  const passwordStrengthText = () => {
    const strength = passwordStrength();
    return ['Très faible', 'Moyen', 'Fort', 'Très fort'][strength] || 'Invalide';
  };

  const strengthTextClass = () => {
    const strength = passwordStrength();
    return {
      'text-red-500': strength === 1,
      'text-yellow-500': strength === 2,
      'text-green-500': strength >= 3,
    };
  };

  const isPasswordStrong = passwordStrength() >= 2;
  const passwordMismatch = newPassword && confirmationPassword && newPassword !== confirmationPassword;

  // Handle form submission

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-purple-50 via-white to-blue-50 px-4">
      <div className="w-full max-w-md p-8 space-y-6 bg-white/80 backdrop-blur-lg rounded-2xl shadow-lg border border-gray-100">
        <div className="text-center">
          <h1 className="text-3xl font-bold bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
            Nouveau mot de passe
          </h1>
          <p className="text-gray-500 mt-2">
            Pour <span className="font-medium text-blue-600">{email}</span>
          </p>
        </div>

        {errorMessage && (
          <div className="p-3 text-sm text-red-700 bg-red-50 rounded-lg">
            {errorMessage}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* New Password Field */}
          <div className="space-y-2">
            <Label htmlFor="newPassword">Nouveau mot de passe</Label>
            <div className="relative">
              <Input
                id="newPassword"
                type={showPassword ? 'text' : 'password'}
                placeholder="••••••••"
                value={newPassword}
                onChange={(e) => setNewPassword(e.target.value)}
                minLength={8}
                autoComplete="new-password"
                required
                className="pl-10 pr-10"
              />
              <Lock className="w-5 h-5 absolute left-3 top-2.5 text-gray-400" />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-2.5 text-gray-400 hover:text-gray-600"
                aria-label={showPassword ? 'Cacher le mot de passe' : 'Afficher le mot de passe'}
              >
                {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
              </button>
            </div>

            {/* Password Strength Feedback */}
            {newPassword && (
              <div className="mt-2">
                <div className="flex space-x-1 h-2">
                  {[1, 2, 3].map((level) => (
                    <div
                      key={level}
                      className={`flex-1 rounded transition-all duration-300 ${
                        passwordStrength() >= level ? 'bg-green-500' : 'bg-gray-300'
                      }`}
                    />
                  ))}
                </div>
                <p className={`text-sm mt-1 ${strengthTextClass()}`}>
                  {passwordStrengthText()}
                  {passwordStrength() < 3 && (
                    <span className="block text-gray-500 text-xs mt-1">
                      (minimum 8 caractères avec majuscule et chiffre)
                    </span>
                  )}
                </p>
              </div>
            )}
          </div>

          {/* Confirm Password Field */}
          <div className="space-y-2">
            <Label htmlFor="confirmationPassword">Confirmer le mot de passe</Label>
            <div className="relative">
              <Input
                id="confirmationPassword"
                type={showconfirmationPassword ? 'text' : 'password'}
                placeholder="••••••••"
                value={confirmationPassword}
                onChange={(e) => setconfirmationPassword(e.target.value)}
                autoComplete="new-password"
                required
                className="pl-10 pr-10"
              />
              <Lock className="w-5 h-5 absolute left-3 top-2.5 text-gray-400" />
              <button
                type="button"
                onClick={() => setShowconfirmationPassword(!showconfirmationPassword)}
                className="absolute right-3 top-2.5 text-gray-400 hover:text-gray-600"
                aria-label={showconfirmationPassword ? 'Cacher le mot de passe' : 'Afficher le mot de passe'}
              >
                {showconfirmationPassword ? <EyeOff size={18} /> : <Eye size={18} />}
              </button>
            </div>
            {passwordMismatch && (
              <p className="text-sm text-red-500 mt-1">
                Les mots de passe ne correspondent pas
              </p>
            )}
          </div>

          {/* Submit Button */}
          <Button
            type="submit"
            disabled={isSubmitting || passwordMismatch || !isPasswordStrong}
            className="w-full bg-purple-600 hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isSubmitting ? (
              <span className="flex items-center justify-center">
                <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                Enregistrement...
              </span>
            ) : (
              "Réinitialiser le mot de passe"
            )}
          </Button>
        </form>

        {/* Back to Login Link */}
        <div className="text-center">
          <Link
            to="/auth/signin"
            className="text-purple-600 hover:underline flex items-center justify-center gap-1"
          >
            <ArrowLeft size={16} />
            Retour à la connexion
          </Link>
        </div>
      </div>
    </div>
  );
};

export default ResetPassword;
