// front avec authentification/Frontend/src/pages/auth/SignIn.tsx
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Link } from "react-router-dom";
import { Eye, EyeOff, Mail, Lock } from "lucide-react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
// Services & Utils
import { authService } from "@/services/authService";
import { decodeToken } from "@/utils/jwt";

const SignIn = () => {
  const [showPassword, setShowPassword] = useState(false);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [errorMessage, setErrorMessage] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const navigate = useNavigate();

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setErrorMessage("");
    
 

    try {
      const response = await authService.login({ email, password });
      
      if (!response.token) {
        throw new Error("No token received from server");
      }

      // Store the token in localStorage
      localStorage.setItem('token', response.token);

      // Immediately decode and update auth state
      const decoded = decodeToken(response.token);
      console.log("Decoded token:", decoded);
      const { roles = [] } = decoded;

      // Use React Router navigation instead of window.location
      if (roles.includes("ROLE_ADMIN")) {
        navigate("/acces/admin");
      } else if (
        roles.includes("ROLE_ETUDIANT") ||
        roles.includes("ROLE_PROFESSEUR") ||
        roles.includes("ROLE_MODERATEUR")
      ) {
        navigate("/app/forum");
      } else {
        navigate("/unauthorized");
      }

    } catch (error) {
      console.error("Login failed", error);
      setErrorMessage(
        (error).response?.data?.message ||
        (error as Error).message ||
        "Erreur de connexion."
      );
    } finally {
      setIsLoading(false);
    }
  };
  
  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-purple-50 via-white to-blue-50">
      <div className="w-full max-w-md p-8 space-y-6 bg-white/80 backdrop-blur-lg rounded-2xl shadow-lg border border-gray-100">
        <div className="text-center">
          <h1 className="text-3xl font-bold bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
            Connexion
          </h1>
          <p className="text-gray-500 mt-2">Connectez-vous à votre compte</p>
        </div>

        {errorMessage && (
          <div className="p-3 text-sm text-red-700 bg-red-50 rounded-lg">
            {errorMessage}
          </div>
        )}

        <form className="space-y-4" onSubmit={handleLogin}>
          <div className="space-y-2">
            <Label>Email</Label>
            <div className="relative">
              <Input
                type="email"
                placeholder="votre@email.com"
                className="pl-10"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
                disabled={isLoading}
              />
              <Mail className="w-5 h-5 absolute left-3 top-2.5 text-gray-400" />
            </div>
          </div>

          <div className="space-y-2">
            <Label>Mot de passe</Label>
            <div className="relative">
              <Input
                type={showPassword ? "text" : "password"}
                placeholder="•••••••••"
                className="pl-10"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
                disabled={isLoading}
              />
              <Lock className="w-5 h-5 absolute left-3 top-2.5 text-gray-400" />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-2.5 text-gray-400 hover:text-gray-600"
                disabled={isLoading}
              >
                {showPassword ? (
                  <EyeOff className="w-5 h-5" />
                ) : (
                  <Eye className="w-5 h-5" />
                )}
              </button>
            </div>
          </div>

          <div className="text-right">
            <Link
              to="/auth/forgot-password"
              className="text-sm text-purple-600 hover:underline"
            >
              Mot de passe oublié ?
            </Link>
          </div>

          <Button
            className="w-full bg-purple-600 hover:bg-purple-700"
            type="submit"
            disabled={isLoading}
          >
            {isLoading ? "Connexion en cours..." : "Se connecter"}
          </Button>
        </form>

        <div className="text-center">
          <p className="text-sm text-gray-600">
            Pas de compte ?{" "}
            <Link
              to="/auth/signup"
              className="text-purple-600 hover:underline"
            >
              Inscrivez-vous
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
};

export default SignIn;

// function refreshAuth() {
//   throw new Error("Function not implemented.");
// }

// We_Connect-main -/src/pages/auth/SignIn.vue
<template>
  <div class="auth-page">
    <div class="auth-card card">
      <div class="text-center space-y-2">
        <h1 class="text-3xl font-bold text-gradient">Connexion</h1>
        <p class="text-gray-500">Connectez-vous à votre compte</p>
      </div>

     

      <form class="space-y-4" @submit.prevent="handleLogin">
        <div class="form-group">
          <label class="label">Email</label>
          <div class="input-wrapper">
            <MailIcon class="input-icon" />
            <input 
              type="email" 
              placeholder="votre@email.com" 
              class="input" 
              v-model="email"
              required
            />
          </div>
        </div>

        <div class="form-group">
          <label class="label">Mot de passe</label>
          <div class="input-wrapper">
            <LockIcon class="input-icon" />
            <input 
              :type="showPassword ? 'text' : 'password'" 
              placeholder="•••••••••" 
              class="input" 
              v-model="password"
              required
            />
            <button
              type="button"
              @click="showPassword = !showPassword"
              class="password-toggle"
              tabindex="-1"
            >
              <EyeOffIcon v-if="showPassword" class="w-5 h-5" />
              <EyeIcon v-else class="w-5 h-5" />
            </button>
          </div>
        </div>

        <div class="text-right">
          <RouterLink to="/auth/forgot-password" class="link text-sm">
            Mot de passe oublié ?
          </RouterLink>
        </div>

        <button type="submit" class="btn btn-primary w-full">
          Se connecter
        </button>
      </form>
      <div v-if="errorMessage" class="alert alert-error mb-4">
        {{ errorMessage }}
      </div>

      <div class="text-center text-sm text-gray-600 mt-4">
        <p>Pas de compte ? <RouterLink to="/auth/signup" class="link">Inscrivez-vous</RouterLink></p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter, RouterLink } from 'vue-router'
import authService from '@/Services/authService'
import { MailIcon, LockIcon, EyeIcon, EyeOffIcon } from 'lucide-vue-next'

const router = useRouter()
const email = ref('')
const password = ref('')
const showPassword = ref(false)
const errorMessage = ref('')

const handleLogin = async () => {
  errorMessage.value = ''
  try {
    const { data } = await authService.login(email.value, password.value)
    console.log('Login success', data)
    router.push('/dashboard')
  } catch (error) {
    console.error('Login failed', error.response?.data || error.message)
    // Handle both 'message' and 'error' keys from backend
    errorMessage.value =
      error.response?.data?.message ||
      error.response?.data?.error ||
      'Erreur de connexion.'
  }
}
</script>

<style scoped>
 .alert {
   background-color: #f8d7da;
   color: #721c24;
   padding: 10px;
   border-radius: 5px;
   margin-top: 10px;
 }
</style>
